# Generated by Django 4.1.13 on 2024-07-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=70, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
